name: lint

on:
  push:
    paths: '**.lua'
    branches: [main, develop]
  pull_request:
    paths: '**.lua'
    types: [opened, synchronize]

jobs:
  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and run selene
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: "."
